### ISSUE TITLE
Runtime error on using --no-db flag

### ISSUE THREAD

**Issue by sting8k** [jaeles-project/jaeles#31]
Command:
`./jaeles scan -s templates/ -u http://testphp.vulnweb.com/listproducts.php?cat=2 -c 50 --no-db`

Error (if using `--no-db`):
```
Jaeles beta v0.14 by @j3ssiejjj
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xb0 pc=0xc4a966]

goroutine 1 [running]:
github.com/jinzhu/gorm.(*DB).clone(0x0, 0x4ebfa4)
	/go/pkg/mod/github.com/jinzhu/gorm@v1.9.16/main.go:853 +0x26
github.com/jinzhu/gorm.(*DB).NewScope(0x0, 0x111fb20, 0xc00012c000, 0xc0004182d0)
	/go/pkg/mod/github.com/jinzhu/gorm@v1.9.16/main.go:204 +0x2f
github.com/jinzhu/gorm.(*DB).Create(0x0, 0x111fb20, 0xc00012c000, 0x1)
	/go/pkg/mod/github.com/jinzhu/gorm@v1.9.16/main.go:482 +0x43
github.com/jaeles-project/jaeles/database.NewScan(0xc0004cc7e0, 0x12, 0x13435a3, 0x1a, 0xc0004ccac0, 0x1b, 0xc0004ccae0, 0x1c, 0xc0004ccb00, 0x1d, ...)
	/go/src/github.com/jaeles-project/jaeles/database/scan.go:37 +0x33e
github.com/jaeles-project/jaeles/cmd.SelectSign()
	/go/src/github.com/jaeles-project/jaeles/cmd/root.go:198 +0x46a
github.com/jaeles-project/jaeles/cmd.runScan(0xc000470580, 0xc0004040e0, 0x0, 0x7, 0x0, 0x0)
	/go/src/github.com/jaeles-project/jaeles/cmd/scan.go:36 +0x42
github.com/spf13/cobra.(*Command).execute(0xc000470580, 0xc000404070, 0x7, 0x7, 0xc000470580, 0xc000404070)
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842 +0x460
github.com/spf13/cobra.(*Command).ExecuteC(0x1fbff40, 0x44813a, 0x1fd5680, 0xc000000180)
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
github.com/jaeles-project/jaeles/cmd.Execute()
	/go/src/github.com/jaeles-project/jaeles/cmd/root.go:33 +0x31
main.main()
	/go/src/github.com/jaeles-project/jaeles/main.go:6 +0x20
```

**Comment by j3ssie** [comment]
What is your OS?

**Comment by sting8k** [comment]
> What is your OS?

Debian 8 x64

**Comment by j3ssie** [comment]
Update Jaeles with this command `GO111MODULE=on go get github.com/jaeles-project/jaeles` then it should be fixed.

**Comment by 0xhunster** [comment]
still, issue here. did not resolve yet.

**Comment by Stonen2** [comment]
I had a similar issue when I first installed Jaeles with the following installation process: 

`GO111MODULE=on go get github.com/jaeles-project/jaeles`

However, installing Jaeles through `go install github.com/jaeles-project/jaeles@latest` did not yield this issue and seems to work as expected.
